#:schema node_modules/wrangler/config-schema.json
name = "rediflare"
main = "src/index.ts"
compatibility_date = "2024-09-25"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[env.staging.vars]
VAR_API_AUTH_ENABLED = true
VAR_API_AUTH_ADMIN_KEYS_CSV = ",rf_key_TENANT1111_sometoken,"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[env.staging.durable_objects]
bindings = [
    {name = "REDIFLARE_TENANT", class_name = "RediflareTenant"},
    {name = "REDIFLARE_REDIRECT_RULE", class_name = "RediflareRedirectRule"},
]

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RediflareTenant", "RediflareRedirectRule"]
